### ISSUE TITLE
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type. 

### ISSUE THREAD

**Issue by oneoyz** [d909b/perfect_match#1]
Hi,
today I tried to play around with this tool with the ihdp data set, but it shows this kind of error when i run the data. 

This is the error looks like:
```
...
    question_marks=",".join(["?"] * len(values[0]))), values)
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.
```
Maybe the code data_access/ihdp/data_access.py at line 128, x not to be defined as ARRAY?

**Comment by d909b** [comment]
Hi @oneoyz - thank you for your interest in our work.

At first glance, it looks like in your setup the custom ARRAY type (SQLite does not have a native ARRAY type) was not defined before the database was connected in data_access.connect:
```
self.db = sqlite3.connect(db_file,
                                  check_same_thread=False,
                                  detect_types=sqlite3.PARSE_DECLTYPES)
```

To avoid code duplication, the custom ARRAY type is only defined in `perfect_match/data_access/tcga/data_access.py`. You therefore either have to import `perfect_match/data_access/tcga/data_access.py` (the provided main.py does this automatically), or call this code manually, before connecting to your SQLite database:

```
def adapt_array(arr):
    """
    SOURCE: http://stackoverflow.com/a/31312102/190597 (SoulNibbler)
    """
    out = io.BytesIO()
    np.save(out, arr)
    out.seek(0)
    return sqlite3.Binary(out.read())


def convert_array(text):
    out = io.BytesIO(text)
    out.seek(0)
    return np.load(out)


sqlite3.register_adapter(np.ndarray, adapt_array)
sqlite3.register_converter("ARRAY", convert_array)
sqlite3.register_converter("DATE", lambda x: datetime.datetime.fromtimestamp(float(x)/1000))
```

**Comment by oneoyz** [comment]
thank you!
