### ISSUE TITLE
Counterfactual Inference for Continuous Treatment

### ISSUE THREAD

**Issue by YangBarry** [d909b/perfect_match#15]
This is a fascinating work! Can this method be extended to the scenario where the treatment is continuous, say, the degree of medication for a patient? One easy modification is to discretize the continuous variable.

**Comment by d909b** [comment]
Hi @YangBarry, great question! the approach you indicated could be a feasible strategy. Have a look also at this follow up work of ours: https://github.com/d909b/drnet

best wishes,
Patrick
